config/routes.rb
Rails.application.routes.draw do

  get 'web' => "web#index", as: :web_index
  get 'web/document/:id' => "web#document", as: :web_document
  get 'web/presentation' , as: :web_presentation
  get 'web/document'
  get 'web/certificado'
  get 'cadastro/cadastrar', as: :cadastrar
  post 'cadastro/cadastrar' => "cadastro#create"

  resources :reply_deeds do
    member do 
      get "delete_eq"
    end
  end

  resources :deeds

  devise_for :users
  resources :configurations

  resources :questions

  resources :comments do
    member do
      post 'editable_edit'
    end
  end

  resources :votes do
    collection do
      post 'create_by_reply'
      get 'receber_voto'
      get 'entrada_sala'
    end
    member do
      get  'plus_vote'
    end
  end

  resources :replies

  resources :documents

  resources :users do
    collection do
      get 'tokens'
    end
  end

  get 'home/index'
  get 'home/credenciamento', as: :credenciamento
  get 'home/painel_credenciamento', as: :painel_credenciamento
  get 'home/painel_cidades', as: :painel_cidades
  get 'home/painel_categorias', as: :painel_categorias
  get 'home/painel_moderador',  as: :painel_moderador
  get 'home/painel_redator', as: :painel_redator
  get 'home/lista_participantes', as: :lista_participantes
  get 'home/plenaria', as: :plenaria
  get 'home/relatorio_evento', as: :relatorio_evento
  get 'home/get_actions', as: :get_actions
  get 'home/painel'
  get 'home/telao', as: :telao
  get 'home/multimidia', as: :multimidia
  get 'home/multimidia_control', as: :multimidia_control
  get 'home/painel_votacao_final', as: :painel_votacao_final
  
  resources :themes do
   

  end

  resources :entries do
    member do
      get "etiqueta"
      get "print"
      get "certificado"
    end
  end

  resources :people

  resources :events do
    member do 
      get 'names'
      get 'votacao_final'
      get 'definir_prioritario'
      get 'retornar_desafios'
      get 'retornar_perguntas_plenarias'
      get 'finalizar_votacao'
      
    end
    collection do
      get "contabilizar_votos"
      get 'contabilizar_votos_plenaria'
    end

  end

  get "credenciar/" => "home#credenciar", as: :credenciar_sem
  get "credenciar/:cpf" => "home#credenciar", as: :credenciar
  get "painel/norteadoras/:question_id/:theme_id" => "home#get_norteadoras", as: :get_norteadoras
  get "painel/sociedade/:question_id/:theme_id" => "home#get_sociedade", as: :get_sociedade

  root 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :question
  belongs_to :theme
  belongs_to :event
  has_paper_trail

  #extend Enumerize
	#self.inheritance_column = nil
	#enumerize :tipo, in: [:tema, :inicio, :fim], predicates: true

	# #Retorna os comentários tipo tema
	scope :tema,-> {where(tipo: :tema)}

	# #Retorna os comentários tipo inicio
	scope :inicio,-> {where(tipo: :inicio)}

	# #Retorna os comentários tipo tema
	scope :fim,-> {where(tipo: :fim)}
	
	# #Ordena os comentários pelo id
	default_scope { order(id: :asc) }

  def tema?
    self.tipo == "tema"
  end

  def inicio?
    self.tipo == "tipo"
  end

  def fim?
    self.tipo == "fim"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :editable_edit]
  skip_before_filter :verify_authenticity_token, :only => :editable_edit
  load_and_authorize_resource except: :create
  
  respond_to :html, :js
  
  #Lista todos os comentários
  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  #Exibe apenas um comentário
  def show
    respond_with(@comment)
  end

  #Exibe o formulário de criação de um comentário
  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  #Exibe o formulario de edição do comentário
  def edit
  end

  #Cria um comentário de acordo com os dados em comment_params
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      if params[:form_type] == "moderador"
        render :moderador_success
      end
    else
      render :error
    end
  end

  #Atualiza um registro através de comment_params
  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  #Apaga um registro
  def destroy
    @comment.destroy
    redirect_to :back
  end


  #Permite a edição através do Jquery plugin X-editable
  def editable_edit
    @comment.text = params[:value]
    render json: @comment.save
  end

  private

    #Busca um comentário via params[:id]
    def set_comment
      @comment = Comment.find(params[:id])
    end

    #Configura os Strong Paramters
    def comment_params
      params.require(:comment).permit(:question_id, :theme_id, :event_id, :text, :tipo)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<style type="text/css">
    .inputor {
      height: 160px;
      width: 90%;
      border: 1px solid #dadada;
      border-radius: 4px;
      padding: 5px 8px;
      outline: 0 none;
      margin: 10px 0;
      background: white;
      font-size: inherit;
      overflow-y: scroll;
    }
</style>
<%= form_for(@comment, remote:true) do |f| %>
<% if @comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

  <ul>
    <% @comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.hidden_field :question_id, value: params[:question_id] %>
<%= f.hidden_field :theme_id, value: params[:theme_id] %>
<%= f.hidden_field :event_id, value: params[:event_id] %>


<%#= f.select :type, Comment.tipo.options, {selected: params[:type]}, {class:"well bg-white strong text-center", style:"width:100%;font-size:15px; display:none"} %>
  <%= f.select :tipo, [["Tema","tema"], ["Início","inicio"], ["Fim","fim"]], {selected: params[:tipo]}, {class:"well bg-white strong text-center", style:"width:100%;font-size:15px; display:none"} %>
<%= f.text_area :text, class:"well bg-white  strong text-center inputor", style:"width:100%;font-size:15px;", placeholder:"Insira aqui o Comentário...", rows:5 ,id:"input"%>
</div>
<div class="actions">
  <% if params[:moderador] == "true" %>
  <%= hidden_field_tag :form_type, :moderador %>

  <%= f.submit "Enviar ao Redator", class:"btn btn-lg btn-success btn-block" %>
  <% else %>
  <%= f.submit "Inserir Comentário", class:"btn btn-lg btn-success btn-block" %>
  <% end %>
</div>
<% end %>

<script type="text/javascript">
  // $(function(){
  //    data = <%= raw Event.find(params[:event_id]).people.pluck(:name).compact.to_json %>;
  //    $('textarea').atwho({at:"@", 'data':data});
  //});

var names = <%= raw Event.find(params[:event_id]).people.distinct.map{|p| {name: p.name, function: p.function, city: p.city.name, cpf: p.cpf}}.to_json
 %>;

var at_config = {
  at: "@",
  data: names,
  tpl: "<li data-value='@${name}'>${name} <small>${cpf}</small></li>",
  show_the_at: true,
  insertTpl: '${name} (${function} | ${city}) ',
  callbacks: {
    matcher: function(flag, subtext, should_start_with_space) {
      var match, regexp;

      flag = flag.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");

      if (should_start_with_space) {
        flag = '(?:^|\\s)' + flag;
      }

      regexp = new RegExp(flag + '([A-Za-z0-9_\\s\+\-\]*)$|' + flag + '([^\\x00-\\xff]*)$', 'gi');
      match = regexp.exec(subtext.replace(/\s/g, " "));
      if (match) {
        return match[2] || match[1];
      } else {
        return null;
      }
    }
  }
}

$('textarea').atwho(at_config)


</script>

app/views/comments/create.js.erb
$("#modal").modal('hide');
swal("Ok!", "Desafio Inserida com Sucesso", "success");
location.reload()

app/views/comments/destroy.js.erb
$("#modal").modal('hide');
swal("Ok!", "Desafio apagada com sucesso!", "success");
$("#replies_question_<%= @vote.reply.question.id  %>").html("<%= escape_javascript(render partial:'home/event_results', locals:{event:@vote.event, theme:@vote.theme, question:@vote.reply.question}) %>")

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/error.js.erb
$("#modal").modal("hide")
swal("Desafio não inserido","<%= escape_javascript(raw @comment.errors.full_messages.to_sentence)  %>", "error")

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Subtheme</th>
      <th>Event</th>
      <th>Text</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.question %></td>
        <td><%= comment.event %></td>
        <td><%= comment.text %></td>
        <td><%= comment.tipo %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/moderador_success.js.erb
$("#modal").modal('hide');
swal("Ok!", "Desafio Inserida com Sucesso", "success");

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/new.js.erb
$("#modal_content").html("<%= escape_javascript(render 'form') %>")
$("#modal").modal('show');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @comment.question %>
</p>


<p>
  <strong>Event:</strong>
  <%= link_to @comment.event.name, @comment.event %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Type:</strong>
  <%= @comment.tipo %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>