config/routes.rb
Rails.application.routes.draw do

  get 'web' => "web#index", as: :web_index
  get 'web/document/:id' => "web#document", as: :web_document
  get 'web/presentation' , as: :web_presentation
  get 'web/document'
  get 'web/certificado'
  get 'cadastro/cadastrar', as: :cadastrar
  post 'cadastro/cadastrar' => "cadastro#create"

  resources :reply_deeds do
    member do 
      get "delete_eq"
    end
  end

  resources :deeds

  devise_for :users
  resources :configurations

  resources :questions

  resources :comments do
    member do
      post 'editable_edit'
    end
  end

  resources :votes do
    collection do
      post 'create_by_reply'
      get 'receber_voto'
      get 'entrada_sala'
    end
    member do
      get  'plus_vote'
    end
  end

  resources :replies

  resources :documents

  resources :users do
    collection do
      get 'tokens'
    end
  end

  get 'home/index'
  get 'home/credenciamento', as: :credenciamento
  get 'home/painel_credenciamento', as: :painel_credenciamento
  get 'home/painel_cidades', as: :painel_cidades
  get 'home/painel_categorias', as: :painel_categorias
  get 'home/painel_moderador',  as: :painel_moderador
  get 'home/painel_redator', as: :painel_redator
  get 'home/lista_participantes', as: :lista_participantes
  get 'home/plenaria', as: :plenaria
  get 'home/relatorio_evento', as: :relatorio_evento
  get 'home/get_actions', as: :get_actions
  get 'home/painel'
  get 'home/telao', as: :telao
  get 'home/multimidia', as: :multimidia
  get 'home/multimidia_control', as: :multimidia_control
  get 'home/painel_votacao_final', as: :painel_votacao_final
  
  resources :themes do
   

  end

  resources :entries do
    member do
      get "etiqueta"
      get "print"
      get "certificado"
    end
  end

  resources :people

  resources :events do
    member do 
      get 'names'
      get 'votacao_final'
      get 'definir_prioritario'
      get 'retornar_desafios'
      get 'retornar_perguntas_plenarias'
      get 'finalizar_votacao'
      
    end
    collection do
      get "contabilizar_votos"
      get 'contabilizar_votos_plenaria'
    end

  end

  get "credenciar/" => "home#credenciar", as: :credenciar_sem
  get "credenciar/:cpf" => "home#credenciar", as: :credenciar
  get "painel/norteadoras/:question_id/:theme_id" => "home#get_norteadoras", as: :get_norteadoras
  get "painel/sociedade/:question_id/:theme_id" => "home#get_sociedade", as: :get_sociedade

  root 'home#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :entries
	has_many :events, through: :entries
	belongs_to :city
	has_paper_trail

	validates :cpf, uniqueness: true
	before_validation :cpf_default

	#extend Enumerize
	#enumerize :category, in: [:sociedade_civil_organizada, :poder_publico, :convidados, :outros], predicates: true
	#
	#
	#

	def sociedade_civil_organizada?
		self.category == "sociedade_civil_organizada"
	end

	def poder_publico?
		self.category == "poder_publico"
	end

	def convidados?
		self.category == "convidados"
	end

	def outros?
		self.category == "outros"
	end

	#Retorna a coluna <tt>name</tt> como padrão em string
	def to_s
		self.name
	end

	#Cadastra o CPF padrão como id do registro caso seja deixado em branco.
	#Isso se faz necessário pois o CPF é exigido como um campo único, mas
	#pode ser deixado em branco. Não sendo possível dois registros com CPF nil.
	def cpf_default
		if self.cpf.blank?			
			self.cpf = Time.now.to_i
		end
	end

	def self.use_api
		true
	end

	#Retorna Person pelo CPF caso exista, ou cria Person via CpfApi caso não exista.
	def self.search_and_create(cpf)
		person = find_by_cpf(cpf)
		if person.blank?
			begin
				if Person.use_api
					data = CpfApi.get_data(cpf)	
				else
					data = {status: 2}
				end
			end
			begin
				sex = data[:genero] == "M" ? "Masculino" : "Feminino"
			rescue
				sex = nil
			end
			if data and data[:status] == 1				
				return  Person.create(
					cpf:cpf,
					name: data[:nome],
					birthdate: data[:nascimento],
					mothername: data[:mae],
					sex: sex
				)
			end
		end
		return person
	end

	#Verifica se o existe um relacionamento entre Person e Theme para determinado Event via Entry.
	#Retorna true ou false
	def have_entry(event, theme)
		entries.where(event: event).where(theme: theme).present?
	end
	
	#Retorna os participantes da consulta pública
	def as_json(person = {})
		jason_person = (person)

		jason_person[:nome] = self.name
		jason_person[:cpf] = self.cpf
		jason_person[:email] = self.email
		jason_person[:categoria] = self.category

		#incluidos posteriormente
		jason_person[:cargo] = self.function
		jason_person[:empresa] = self.company
		jason_person[:sexo] = self.sex
		jason_person[:cidade] = self.city_id
		jason_person[:tag] = self.entries.select(:tags).where(:person_id == self.id).order(id: :asc).last.tags
		jason_person[:data] = self.birthdate
		jason_person[:mae] = self.mothername

		jason_person
	end

	
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_person, only: [:show, :edit, :update, :destroy, :as_json]
  load_and_authorize_resource except: :create
  
  # GET /people
  # GET /people.json
  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true).page(params[:page]).per(10)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:cpf, :name, :phone, :email, :function, :sex, :company)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="widget media margin-none bg-gray ">
      <a class="pull-left bg-info innerAll text-center text-white"><i class="fa icon-user-2 fa-5x"></i></a>
      <div class="media-body innerAll">
        <h4 class="media-heading innerT"> Gerenciar Pessoa</h4>                     
        <p>Gerenciamento de Participantes</p>
      </div>
      <div class="widget-body bg-white">
        
        <div class="col-md-6">
          <div class="field">
            <%= f.label :name, "Nome" %>
            <%= f.text_field :name, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>
        
        <div class="col-md-6">
          <div class="field">
            <%= f.label :cpf, "CPF" %>
            <%= f.text_field :cpf, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :mothername, "Nome da Mãe" %>
            <%= f.text_field :mothername, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :company, "Empresa/Órgão" %>
            <%= f.text_field :company, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :phone, "Telefone" %>
            <%= f.text_field :phone, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :email, "E-mail" %>
            <%= f.text_field :email, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :function, "Função" %>
            <%= f.text_field :function, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field">
            <%= f.label :birthdate, "Data de Aniversário" %>
            <%= f.date_field :birthdate, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <!-- <div class="col-md-6">
          <div class="field">
            <%#= f.label :sex, "Sexo" %>
            <%#= f.text_field :sex, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div> -->

        <div class="col-md-6">
          <div class="field">
            <%= f.label :category, "Vinculo" %>
            <%= f.text_field :category, class:"form-control" %>
            <p>&nbsp;</p>
          </div>
        </div>

        <div class="col-md-12 innerAll inner-2x">
          <%= f.submit "Salvar Participante", class:"btn btn-lg btn-success btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>
<p>&nbsp;</p>
<% end %>

app/views/people/edit.html.erb
<%= render 'form' %>

app/views/people/index.html.erb
<div class="widget">
  <!-- Category Heading -->
  <%= search_form_for @q do |f| %>
  <div class="input-group input-group-lg border-bottom">
    <span class="input-group-btn">
      <a href="" class="btn"><i class="fa fa-search text-muted"></i></a>
    </span>
    <%= f.text_field :name_or_cpf_cont, class: "form-control border-none", placeholder:"Pesquisa" %>
  </div>
  <% end %>
  <% @people.each do |person| %>

  <div class="bg-gray-hover overflow-hidden">
    <div class="row innerAll half border-bottom">

      <div class="col-sm-6 col-xs-8">
        <ul class="media-list margin-none">
          <li class="media">
            <a class="pull-left innerAll half " href="#">
              <span class="empty-photo">
                <i class="text-muted fa fa-user"></i>
              </span>
            </a>
            <div class="media-body">
              <div class="innerAll half">
                <h4 class="margin-none">                
                  <%= link_to person.name, person  %>               
                </h4>
                <div class="clearfix">                
                </div>
                <small class="margin-none text-muted"><%= person.cpf %> | <%= person.function %></small>
              </div>
            </div>

          </li>
        </ul>
      </div>

      <div class="col-sm-3 col-xs-hidden margin-none">
        <div class="innerAll half">
          <div class="media">
            <div class="media-body ">
              <span class="text-small">Desde</span>
              <div class="clearfix"></div>
              <small><%= person.created_at  %></small>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-3 col-xs-hidden margin-none">
        <div class="innerAll half">
          <div class="media">
            <div class="media-body ">
              <%= link_to :editar, edit_person_path(person), class:"btn btn-info" %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <% end %>
</div>
<%= paginate @people %>

app/views/people/new.html.erb
<%= render 'form' %>

app/views/people/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="widget innerAll inner-2x center">
    <h1><%= @person  %></h1>
  </div>
  <div class="widget-body">
    <table class="table table-condensed table-striped table-primary table-vertical-center checkboxs">
      <thead>
        <th>Evento</th>
        <th class="col-md-5">Ações</th>
      </thead>  
      <tbody>
        <% @person.entries.each do |entry| %>
          <tr>
            <td><%= entry.event.name  %> - <%= entry.theme %></td> 
            <td>
              <%= link_to "Imprimir", print_entry_path(entry), class:"btn btn-info btn-sm no-ajaxify", remote: true%>
              <%= link_to "Certificado", certificado_entry_path(entry), class:"btn btn-info btn-sm no-ajaxify"%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>