config/routes.rb
Rails.application.routes.draw do

  get 'web' => "web#index", as: :web_index
  get 'web/document/:id' => "web#document", as: :web_document
  get 'web/presentation' , as: :web_presentation
  get 'web/document'
  get 'web/certificado'
  get 'cadastro/cadastrar', as: :cadastrar
  post 'cadastro/cadastrar' => "cadastro#create"

  resources :reply_deeds do
    member do 
      get "delete_eq"
    end
  end

  resources :deeds

  devise_for :users
  resources :configurations

  resources :questions

  resources :comments do
    member do
      post 'editable_edit'
    end
  end

  resources :votes do
    collection do
      post 'create_by_reply'
      get 'receber_voto'
      get 'entrada_sala'
    end
    member do
      get  'plus_vote'
    end
  end

  resources :replies

  resources :documents

  resources :users do
    collection do
      get 'tokens'
    end
  end

  get 'home/index'
  get 'home/credenciamento', as: :credenciamento
  get 'home/painel_credenciamento', as: :painel_credenciamento
  get 'home/painel_cidades', as: :painel_cidades
  get 'home/painel_categorias', as: :painel_categorias
  get 'home/painel_moderador',  as: :painel_moderador
  get 'home/painel_redator', as: :painel_redator
  get 'home/lista_participantes', as: :lista_participantes
  get 'home/plenaria', as: :plenaria
  get 'home/relatorio_evento', as: :relatorio_evento
  get 'home/get_actions', as: :get_actions
  get 'home/painel'
  get 'home/telao', as: :telao
  get 'home/multimidia', as: :multimidia
  get 'home/multimidia_control', as: :multimidia_control
  get 'home/painel_votacao_final', as: :painel_votacao_final
  
  resources :themes do
   

  end

  resources :entries do
    member do
      get "etiqueta"
      get "print"
      get "certificado"
    end
  end

  resources :people

  resources :events do
    member do 
      get 'names'
      get 'votacao_final'
      get 'definir_prioritario'
      get 'retornar_desafios'
      get 'retornar_perguntas_plenarias'
      get 'finalizar_votacao'
      
    end
    collection do
      get "contabilizar_votos"
      get 'contabilizar_votos_plenaria'
    end

  end

  get "credenciar/" => "home#credenciar", as: :credenciar_sem
  get "credenciar/:cpf" => "home#credenciar", as: :credenciar
  get "painel/norteadoras/:question_id/:theme_id" => "home#get_norteadoras", as: :get_norteadoras
  get "painel/sociedade/:question_id/:theme_id" => "home#get_sociedade", as: :get_sociedade

  root 'home#index'

end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
	has_paper_trail
	validates :token, uniqueness: true
	validates :token, presence: true

	#Retorna o texto como string quando chamado o objeto
	def to_s
		self.text
	end

	#Busca uma configuração pelo token e retorna seu texto quando existir
	def self.get(token)
		Configuration.find_by_token(token) || "configuration::#{token}"
	end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_configuration, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: :create
  
  respond_to :html

  #Lista todos os registros
  def index
    @configurations = Configuration.all
    respond_with(@configurations)
  end

  #Exibe um registro específico
  def show
    respond_with(@configuration)
  end

  #Exibe o formulário de adição de registro
  def new
    @configuration = Configuration.new
    respond_with(@configuration)
  end

  #Exibe o formulário de edição de registro
  def edit
  end

  #Cria um registro com base em params
  def create
    @configuration = Configuration.new(configuration_params)
    @configuration.save
    respond_with(@configuration)
  end

  #Atualiza um registro
  def update
    @configuration.update(configuration_params)
    respond_with(@configuration)
  end

  #Apaga um registro
  def destroy
    @configuration.destroy
    respond_with(@configuration)
  end

  private
    def set_configuration
      @configuration = Configuration.find(params[:id])
    end

    def configuration_params
      params.require(:configuration).permit(:token, :text)
    end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/_form.html.erb
<%= form_for(@configuration) do |f| %>
  <% if @configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@configuration.errors.count, "error") %> prohibited this configuration from being saved:</h2>

      <ul>
      <% @configuration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/configurations/edit.html.erb
<h1>Editing configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @configuration %> |
<%= link_to 'Back', configurations_path %>

app/views/configurations/index.html.erb
<h1>Listing configurations</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configurations.each do |configuration| %>
      <tr>
        <td><%= configuration.token %></td>
        <td><%= configuration.text %></td>
        <td><%= link_to 'Show', configuration %></td>
        <td><%= link_to 'Edit', edit_configuration_path(configuration) %></td>
        <td><%= link_to 'Destroy', configuration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Configuration', new_configuration_path %>

app/views/configurations/new.html.erb
<h1>New configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', configurations_path %>

app/views/configurations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Token:</strong>
  <%= @configuration.token %>
</p>

<p>
  <strong>Text:</strong>
  <%= @configuration.text %>
</p>

<%= link_to 'Edit', edit_configuration_path(@configuration) %> |
<%= link_to 'Back', configurations_path %>