config/routes.rb
Rails.application.routes.draw do

  get 'web' => "web#index", as: :web_index
  get 'web/document/:id' => "web#document", as: :web_document
  get 'web/presentation' , as: :web_presentation
  get 'web/document'
  get 'web/certificado'
  get 'cadastro/cadastrar', as: :cadastrar
  post 'cadastro/cadastrar' => "cadastro#create"

  resources :reply_deeds do
    member do 
      get "delete_eq"
    end
  end

  resources :deeds

  devise_for :users
  resources :configurations

  resources :questions

  resources :comments do
    member do
      post 'editable_edit'
    end
  end

  resources :votes do
    collection do
      post 'create_by_reply'
      get 'receber_voto'
      get 'entrada_sala'
    end
    member do
      get  'plus_vote'
    end
  end

  resources :replies

  resources :documents

  resources :users do
    collection do
      get 'tokens'
    end
  end

  get 'home/index'
  get 'home/credenciamento', as: :credenciamento
  get 'home/painel_credenciamento', as: :painel_credenciamento
  get 'home/painel_cidades', as: :painel_cidades
  get 'home/painel_categorias', as: :painel_categorias
  get 'home/painel_moderador',  as: :painel_moderador
  get 'home/painel_redator', as: :painel_redator
  get 'home/lista_participantes', as: :lista_participantes
  get 'home/plenaria', as: :plenaria
  get 'home/relatorio_evento', as: :relatorio_evento
  get 'home/get_actions', as: :get_actions
  get 'home/painel'
  get 'home/telao', as: :telao
  get 'home/multimidia', as: :multimidia
  get 'home/multimidia_control', as: :multimidia_control
  get 'home/painel_votacao_final', as: :painel_votacao_final
  
  resources :themes do
   

  end

  resources :entries do
    member do
      get "etiqueta"
      get "print"
      get "certificado"
    end
  end

  resources :people

  resources :events do
    member do 
      get 'names'
      get 'votacao_final'
      get 'definir_prioritario'
      get 'retornar_desafios'
      get 'retornar_perguntas_plenarias'
      get 'finalizar_votacao'
      
    end
    collection do
      get "contabilizar_votos"
      get 'contabilizar_votos_plenaria'
    end

  end

  get "credenciar/" => "home#credenciar", as: :credenciar_sem
  get "credenciar/:cpf" => "home#credenciar", as: :credenciar
  get "painel/norteadoras/:question_id/:theme_id" => "home#get_norteadoras", as: :get_norteadoras
  get "painel/sociedade/:question_id/:theme_id" => "home#get_sociedade", as: :get_sociedade

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :get_inicial_params, only:[
    :painel_moderador, :painel_redator, :lista_participantes, 
    :plenaria, :relatorio_evento,:painel_cidades, :painel_credenciamento,
    :painel_categorias, :telao, :painel_votacao_final
  ]
  before_action :get_credenciamento, only:[:painel_cidades, :painel_credenciamento,:painel_categorias]
  #load_and_authorize_resource :class => false
  
  #Lista todos os registros
  def index
  end

  #Exibe a página incial de credenciamento
  def credenciamento
  end

  #Exibe o painel do Moderador
  def painel_moderador
  end

  #Exibe a página para votação final
  def painel_votacao_final
    @event = Event.find(params[:event_id])
  end

  #Exibe o Plenária
  def plenaria
    @deed_ranking = @event.deed_ranking(@theme)
    render layout: 'plenaria'
  end

  #Exibe o Painel no Telão
  def telao
    @themes = Theme.all
    render layout: 'plenaria'
  end

  #Exibe o Relatório do Evento
  def relatorio_evento
    @deed_ranking = @event.deed_ranking_full
    @ranking_priority = @event.ranking_priority.take(10)
    respond_to do |format|
      format.docx{render filename:"#{@event}.docx", layout: false}
      format.html
    end
  end

  #Exibe o Painel do redator
  def painel_redator
    @comments_inicio =  @event.comments.inicio.where(theme:@theme)
    @comments_fim =  @event.comments.fim.where(theme:@theme)
    @deed_ranking = @event.deed_ranking(@theme)
    respond_to do |format|
      format.docx{render filename:"#{@theme} - #{@event}.docx", layout: false}
      format.html
    end
  end

  #Ainda não definido
  def painel
  end

  #Exibe o Painel de Credenciamento
  def painel_credenciamento
  end

  #Exibe o Painel com as informações das entradas por categoria
  def painel_categorias    
  end

  #Exibe os participantes cadastrados para o tema e evento
  def lista_participantes    
  end

  #Exibe um form de Entry no modal
  def credenciar
    @entry = Entry.new
    @person = Person.search_and_create(params[:cpf])
    @entry.event = Event.get_today
    @events = Event.all.map { |e| [e.name, e.id] }
    @themes = Theme.all.map { |e| [e.name, e.id] }
    @cities = City.all.map { |e| [e.name, e.id] }
    @entry.person = @person || Person.new
    respond_to do |format|
      format.js
    end
  end

  #Exibe as respostas cadastradas com default= true
  def get_actions
    @theme = Theme.find(params[:theme_id])
    @event = Event.find(params[:event_id])
    @deed_ranking = @event.deed_ranking(@theme)
    respond_to :js
  end

  #Exibe as respostas cadastradas como sociedade
  def get_sociedade
    @question = Question.find(params[:question_id])
    @theme = Theme.find(params[:theme_id])
    #binding.pry
    @q = Reply.ransack(params[:q])
    @replies = @q.result
    respond_to :js
  end

  def multimidia
    @entries = Entry.count
    @problems = Reply.count
    @actions= Deed.count
    respond_to do |format|
      format.html{render layout: 'plenaria'}
      format.js
    end
  end

  def multimidia_control
    render layout: 'plenaria'
  end

  private

    #Seta as informações iniciais dos paineis ou exibe um formulario para tanto
    def get_inicial_params
      begin
        @event = Event.find(params[:event_id])
        @theme = Theme.find(params[:theme_id])
      rescue
        render "select_params"
      end
      @questions = Question.all.order(id: :asc)
    end

    #Busca o evento do dia
    def get_credenciamento
      @themes = Theme.capacity_dashboard(@event)
      respond_to do |format|
        format.js
        format.html
      end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_deeds_result.html.erb
<div class="media-body innerAll">
	<div class="widget-head">
		<h4 class="heading">Ações</h4>
	</div>
	<div class="widget-body">				
		<ul class="list-group list-group-1 margin-none borders-none">
		<% deed_ranking.each do |ranking| %>
			<li class="list-group-item animated fadeInUp">
				<a>
					<span class="badge pull-right badge-default"><%= ranking[:count]  %></span>
					<%= ranking[:deed] %>
				</a>
			</li>
		<% end %>
		</ul>
	</div>
</div>

app/views/home/_names_telao_1.html.erb
<div class="widget inner-2x innerAll bg-info">		

	<h1 class="center strong" style="font-size:90px;"><%= person  %></h1>
	<h1 class="center "><%= person.function  %> <%= "|" if person.function.present? and person.city.present? %> <%= person.city %></h1>
</div>
<p>&nbsp;</p>
<h1 class="center">
<i class="fa fa-thumbs-up"></i> Obrigado por vir <%= person.name.split(" ").first  %>!
</h1>

app/views/home/_norteadoras.html.erb
<div class="widget">	
	<div class="widget-head">
        <h4 class="heading">
        	Geral
        </h4>
    </div>
   	<div class="widget-body innerAll">        
		<% Reply.where(question:question, subtheme:nil, default:true).each do |reply|  %>
		<div class="widget">
			<div class="widget-head">
				<%= form_tag(create_by_reply_votes_path(event_id:params[:event_id], reply_id:reply.id, theme_id:theme.id), remote: true) do  %>	
					<div class="input-group pull-right" style="width:105px;">
						<%= text_field_tag :value, nil, class:"form-control", placeholder:"Votos"  %>
						<div class="input-group-btn">
							<%= submit_tag("ok", class:"btn btn-success") %>
						</div>
					</div>
				<% end %>
				<h4 class="heading"><%= reply  %></h4>
			</div>
			<div class="widget-body inner-all">
				<p><%= reply.description  %></p>
			</div>
		</div>
        <% end %>
    </div>
    <p>&nbsp;</p>
</div>

<% if question.all_replies %>
	<% Theme.all.each do |theme| %>
		<% theme.subthemes.each do |subtheme| %>
			<div class="widget">	
				<div class="widget-head">
			        <h4 class="heading">
			        	<%= subtheme %>
			        </h4>
			    </div>
			   	<div class="widget-body innerAll">        
					<% Reply.by_theme_question(subtheme, question).norteadoras.each do |reply|  %>
					<div class="widget">
						<div class="widget-head">				
							<%= form_tag(create_by_reply_votes_path(event_id:params[:event_id], reply_id:reply.id, theme_id:theme.id), remote: true) do  %>	
								<div class="input-group pull-right" style="width:105px;">
									<%= text_field_tag :value, nil, class:"form-control", placeholder:"Votos"  %>
									<div class="input-group-btn">
										<%= submit_tag("ok", class:"btn btn-success") %>
									</div>
								</div>
							<% end %>
							<h4 class="heading"><%= reply  %></h4>
						</div>
						<div class="widget-body inner-all">
							<p><%= reply.description  %></p>		
						</div>
					</div>
			        <% end %>
			    </div>
			    <p>&nbsp;</p>
			</div>
			<% end %>
	<% end %>
<% else %>
	<% theme.subthemes.each do |subtheme| %>
	<div class="widget">	
		<div class="widget-head">
	        <h4 class="heading">
	        	<%= subtheme %>
	        </h4>
	    </div>
	   	<div class="widget-body innerAll">        
			<% Reply.by_theme_question(subtheme, question).norteadoras.each do |reply|  %>
			<div class="widget">
				<div class="widget-head">				
					<%= form_tag(create_by_reply_votes_path(event_id:params[:event_id], reply_id:reply.id, theme_id:theme.id), remote: true) do  %>	
						<div class="input-group pull-right" style="width:105px;">
							<%= text_field_tag :value, nil, class:"form-control", placeholder:"Votos"  %>
							<div class="input-group-btn">
								<%= submit_tag("ok", class:"btn btn-success") %>
							</div>
						</div>
					<% end %>
					<h4 class="heading"><%= reply  %></h4>
				</div>
				<div class="widget-body inner-all">
					<p><%= reply.description  %></p>		
				</div>
			</div>
	        <% end %>
	    </div>
	    <p>&nbsp;</p>
	</div>
	<% end %>
<% end %>

app/views/home/_refresh_painel.erb
<%= content_for :scripts do  %>
<script type="text/javascript">
	setInterval(function(){
		$.get("<%= url_for(params) %>")
	}, 10000);
</script>
<% end %>

app/views/home/_sociedade.html.erb
<% if replies.blank? %>
	<h4>Não foram encontrados desafios anteriores</h4>
<% end %>
<% replies.each do |reply|  %>
	<div class="widget">
		<div class="widget-head">				
			<%= form_tag(create_by_reply_votes_path(event_id:params[:event_id], reply_id:reply.id, theme_id:theme.id), remote: true) do  %>	
				<div class="input-group pull-right">
					<%= hidden_field_tag :value, 0, class:"form-control", placeholder:"Votos"  %>
					<div class="input-group-btn">
					</div>
					<%= submit_tag("inserir", class:"btn btn-success") %>
				</div>
			<% end %>
		</div>
		<div class="widget-body inner-all">
			<h4 class="heading"><%= reply  %></h4>
			<p><%= reply.description  %></p>		
		</div>
	</div>
<% end %>
<p>&nbsp;</p>
<%= link_to "Inserir Desafio Personalizado", new_vote_path(event_id:params[:event_id], theme_id:params[:theme_id], question_id:1, title: params[:q][:title_or_description_cont]), class:"btn btn-success btn-lg btn-block strong no-ajaxify", remote: true %>

app/views/home/_votes_question_plenaria.html.erb
<div class="widget media margin-none ">
	<a class="pull-left bg-info innerAll text-center text-white"><i class="fa fa-fw fa-5x"><%= index +1 %></i>
	</a>
	<div class="media-body innerAll">
		<h1 class="media-heading innerT">
			<%= vote.reply %> 
			<small><i class="fa fa-fw fa-comment-o"></i> <%= vote.value %></small>
		</h1>
		<%= vote.reply.description %>
		<p>&nbsp;</p>
	</div>
</div>

app/views/home/acesso_negado.html.erb
<div class="error innerAll ">
	<div class="well text-center">
		<div class="center text-large innerAll">
			<i class="fa fa-5x fa-chain-broken text-danger "></i>
		</div>
		<h1 class="strong innerTB">Acesso Negado</h1>
		<h4 class="innerB">Você não tem permissão de acesso a esta página.</h4>
	</div>
</div>

app/views/home/painel_cidades.js.erb
$("#stats").html("<%= escape_javascript(render partial:'home/cities_entries', locals:{event:@event, themes:@themes}) %>")

app/views/home/painel_moderador.html.erb
<%= content_for :head do  %>
<link href="/chart/chartist.min.css" media="screen, projector, print" rel="stylesheet" type="text/css" />
<script src="/chart/chartist.js"></script>
<script type="text/javascript" src="/drw/js/sketch.js"></script>
<link rel="stylesheet" type="text/css" href="/drw/css/canvas_style.css">
<script type="text/javascript" src="/flipclock/flipclock.js"></script>
<link rel="stylesheet" href="/flipclock/flipclock.css">
<% end %>
<style type="text/css" id="style_grid">
	.grid_votes{display: block;}.table_votes{display: none;}
</style>
<div class="row">	
	<div class="col-md-6">
		<div class="widget media margin-none ">
		<%= link_to @theme, class:"pull-left bg-#{@theme.color} innerAll text-center text-white" do %>
			<i class="fa fa-fw <%= @theme.icon  %> fa-5x"></i>
			<% end %>
			<div class="media-body innerAll">
				<h4 class="media-heading innerT">
				<%= link_to @theme,  @theme, class:"text-inverse" %> 
				</h4>
				<%= @theme.subthemes.count %> Programas
			</div>
		</div>
		<p>&nbsp;</p>
	</div>
	<div class="col-md-3">
		<div class="widget innerAll inner-2x center" style="height:102px">
			<h2><%= @theme.total_subscribers(@event)  %> Participantes</h2>
		</div>
	</div>
	<div class="col-md-3">
		<div class="widget" style="height:102px">
			<div class="timer_moderador" style="margin:2em;"></div>
		</div>
	</div>
</div>
<div class="relativeWrap">
	<div class="widget widget-tabs widget-tabs-double widget-tabs-vertical row row-merge">
		<!-- Tabs Heading -->
		<div class="widget-head col-md-3">
			<ul>
				<% @questions.each do |question| %>
				<li class="">
					<a href="#question-<%= question.id  %>" class="glyphicons circle_question_mark" data-toggle="tab">
						<i></i><span class="strong"><%= question %></span>
					</a>
				</li>
				<% end %>
				<li class="">
					<a href="#draw_painel" class="glyphicons pencil" data-toggle="tab">
						<i></i><span class="strong">Painel de Desenho</span>
						<span>Desenhe para Ilustrar</span>
					</a>
				</li>
				<li class="">
					<a href="#timer" class="glyphicons clock" data-toggle="tab">
						<i></i><span class="strong">Admninistrar o Tempo</span>
						<span>Gerencie o Cronômetro</span>
					</a>
				</li>
				<li class="">
					<a href="<%= contabilizar_votos_events_path(event_id: @event, theme_id: @theme) %>" class="glyphicons stats" >
						<i></i><span class="strong">Contabilizar votos</span>
						<span>Conta votos da sala</span>
					</a>
				</li>
				<li class="">
					<a href="<%= ControlApi.provider %>/consultas_publicas/receber_pergunta?event_id=<%=@event.id%>&theme_id=<%=@theme.id%>" class="glyphicons stats" target="_blank" >
						<i></i><span class="strong">Enviar para Votação</span>
						<span>Envia desafios</span>
					</a>
				</li>
			</ul>
		</div>
		<!-- // Tabs Heading END -->
		<div class="widget-body col-md-9">
			<div class="tab-content">
				<!-- Tab content -->
				<% @questions.each do |question| %>
				<div class="tab-pane animated fadeInUp" id="question-<%= question.id  %>">
					<div class="widget">
						<div class="widget-body innerAll inner-2x">							
							<h4 class="strong center"><%= question  %></h4>
						</div>
					</div>
					<div class="widget innerAll inner-2x">						
						<%= form_tag get_sociedade_path(question, @theme, event_id:@event.id), :method => 'get', remote: true do %>
							<%= fields_for :q do |f|%>
								<%= f.text_field :title_or_description_cont,  class:"well bg-white text-danger strong text-center keyup", style:"width:100%;font-size:25px;", placeholder:"Insira um desafio" %>
							<% end %>
							<%= submit_tag("Pesquisar Desafio", class:"btn-success btn btn-lg btn-block") %>
						<% end %>
					</div>
					<div id="replies_<%= question.id  %>">
						<%= render partial:'home/replies_questions', locals:{event:@event, theme:@theme, question:question} %>
					</div>
					<div id="replies_question_<%= question.id  %>">
						<%= render partial:'home/event_results', locals:{event:@event, theme:@theme, question:question} %>
					</div>
					<%= link_to get_actions_path(event_id:@event.id, theme_id:@theme.id), remote: true, class:"no-ajaxify btn btn-success btn-lg btn-block" do %>
						<i class="icon-trophy-fill fa"></i> Ranking das Ações
					<% end %>
				</div>
				<% end %>
				<div class="tab-pane animated fadeInUp" id="draw_painel">
					<h4>Painel de Desenho</h4>
					<p>&nbsp;</p>
					<%= render 'draw_panel' %>
				</div>
				<div class="tab-pane animated fadeInUp" id="timer">
					<h4>Gerenciamento do tempo</h4>
					<p>&nbsp;</p>
					<%= text_field_tag(:clock, nil, id:"clock", class:"well bg-white text-danger strong text-center", style:"width:100%;font-size:40px;",placeholder:"Minutos") %>
					<a onclick="set_clock()" class="btn btn-success btn-block btn-lg">Iniciar Cronômetro</a>
					<p>&nbsp;</p>
					<div class="row">						
						<div class="col-md-6">						
							<a onclick="clock.stop()" class="btn btn-danger btn-block btn-lg" id="stop_timer">Parar Cronômetro</a>
							<a onclick="clock.start()" class="btn btn-warning btn-block btn-lg" id="start_timer" style="display:none">Reiniciar Cronômetro</a>
						</div>
						<div class="col-md-6">						
							<a onclick="clock.setTime(0)" class="btn btn-info btn-block btn-lg">Zerar Cronômetro</a>
						</div>
					</div>
				</div>
				<div class="tab-pane animated fadeInUp active" id="inicio">
					<h1>Bem Vindo ao PPA 2020/2023</h1>
					<div id="lipsum">
					<h2>
						O que é o PPA?
					</h2>
					<p>O Plano Plurianual é uma lei de iniciativa do Poder Executivo, prevista no art. 165 da Constituição Federal, que estabelecerá, de forma regionalizada, as diretrizes, objetivos e metas da administração pública  para um período de 4 (quatro) anos.</p>
					<h2>
						Objetivos
					</h2>
					<p>
						Realizar as consultas públicas para subsidiar a elaboração do Plano Plurianual 2020-2023.
					</p>
					</div>						
				</div>
			</div>
		</div>
	</div>


<script type="text/javascript">
	var clock;
	setTimeout(function(){ 
		clock = $('.timer_moderador').FlipClock(0, {clockFace: 'MinuteCounter', countdown: true,
			callbacks: {
	        	stop: function() {
	        		if (clock.getTime() < 2) {
	        			swal("Tempo Esgotado", "O tempo configurado para o timer terminou!", "info");
	        		};
	        		$('#stop_timer').hide()
	        		$('#start_timer').show()
	        	}, 
	        	start: function() {
	        		$('#stop_timer').show()
	        		$('#start_timer').hide()
	        	}
	        }
	})
	}, 300);
	
	function set_clock() {
		clock.setTime($('#clock').val()*60)
		clock.start()
	};

	function remove_vote_action (id) {
		$.ajax({
			url: "<%= reply_deeds_path %>/" + id,
			type: 'DELETE'
		});
	}

	function remove_all_vote_action (id) {
		$.get("<%= reply_deeds_path %>/" + id + "/delete_eq")
	}

	function display_table () {
		$('#style_grid').html(".grid_votes{display: none;}.table_votes{display: block;}")
	}

	function display_grid () {
		$('#style_grid').html(".grid_votes{display: block;}.table_votes{display: none;}")
	}
</script>

app/views/home/plenaria.html.erb
<%= content_for :head do  %>
<link href="/chart/chartist.min.css" media="screen, projector, print" rel="stylesheet" type="text/css" />
<script src="/chart/chartist.js"></script>
<script type="text/javascript" src="/drw/js/sketch.js"></script>
<link rel="stylesheet" type="text/css" href="/drw/css/canvas_style.css">
<script type="text/javascript" src="/flipclock/flipclock.js"></script>
<link rel="stylesheet" href="/flipclock/flipclock.css">
<% end %>
<div class="row">	
	<div class="col-md-6">
		<div class="widget media margin-none ">
			<%= link_to plenaria_path, class:"pull-left bg-#{@theme.color} innerAll text-center text-white" do %>
			<i class="fa fa-fw <%= @theme.icon  %> fa-5x"></i>
			<% end %>
			<div class="media-body innerAll">
				<h4 class="media-heading innerT">
					<%= link_to @theme, plenaria_path,  class:"text-inverse" %> 
				</h4>
				<%= @theme.subthemes.count %> Programas
			</div>
		</div>
		<p>&nbsp;</p>
	</div>
	<div class="col-md-3">
		<div class="widget innerAll inner-2x center" style="height:102px">
			<h2><%= @theme.total_subscribers(@event)  %> Participantes</h2>
		</div>
	</div>
	<div class="col-md-3">
		<div class="widget innerAll inner-2x center" style="height:102px">
			<h2><%= @event.place  %></h2>
		</div>
	</div>
</div>

<div class="relativeWrap">
	<div class="widget widget-4 widget-tabs-icons-only margin-bottom-none">
		<!-- Widget Heading -->
		<div class="widget-head">
			<!-- Tabs -->
			<ul class="pull-left">
				<li class="glyphicons display active">
					<span data-toggle="tab" data-target="#theme_tab"><i>1</i>
					</span>
				</li>
				<li class="glyphicons notes_2">
					<span data-toggle="tab" data-target="#subtheme_tab"><i>2</i>
					</span>
				</li>
				<% @questions.each do |question| %>
				<% question.votes_theme_ranking(@theme, @event).each_with_index do |vote,index| %>
				<li class="glyphicons">
					<span data-toggle="tab" data-target="#question_<%= question.id  %>_<%= index + 3  %>"><i class="text-inverse"><%= index + 1 %></i>
					</span>
				</li>
				<% end %>
				<% end %>
				<li class="glyphicons list">
					<span data-toggle="tab" data-target="#tab4-7"><i></i>
					</span>
				</li>
				<li class="glyphicons pie_chart" onclick="ver_grafico_1()">
					<span data-toggle="tab" data-target="#tab4-6"><i></i>
					</span>
				</li>
				<li class="glyphicons cup">
					<span data-toggle="tab" data-target="#tab4-5"><i></i>
					</span>
				</li>
			</ul>
			<% if params[:action] == "presentation" %>
				&nbsp; << Utilize o menu para passar os slides
			<% end %>
			<div class="clearfix"></div>
			<!-- // Tabs END -->
		</div>
		<!-- Widget Heading END -->
		<div class="widget-body">
			<div class="tab-content">
				<!-- Tab content -->
				<div id="theme_tab" class="tab-pane active box-generic bg-<%= @theme.color %> center text-large innerAll inner-2x text-white">
					<p>&nbsp;</p>
					<i class="fa fa-fw <%= @theme.icon  %> fa-5x"></i>
					<p>&nbsp;</p>
					<%= @theme  %>
					<p>&nbsp;</p>
				</div>
				<!-- // Tab content END -->
				<!-- Tab content -->
				<div id="subtheme_tab" class="tab-pane box-generic">
					<h1>Programas</h1>
					<div class="widget"></div>
					<div class="innerAll inner-2x">						
						<ul>
							<% @theme.subthemes.each do |subtheme| %>
							<li><h2> <%= subtheme  %> </h2></li>
							<% end %>
						</ul>
					</div>
				</div>
				<!-- // Tab content END -->	
				<!-- Tab content -->
				<% @questions.each do |question| %>
				<% question.votes_theme_ranking(@theme, @event).each_with_index do |vote,index| %>
				<div id="question_<%= question.id  %>_<%= index + 3  %>" class="tab-pane box-generic">
					<h1><%= vote.reply %></h1>
					<p>&nbsp;</p>
					<div class="widget widget-heading-simple widget-body-white " onclick="pulse_it($(this))">
						<div class="widget-body innerAll inner-2x">
							<i class="fa fa-comments fa fa-4x pull-left fa fa-muted"></i>
							<h2 class="innerAll center strong"><%= vote.reply.description %></h2>
						</div>
					</div>
					<div class="bg-<%= @theme.color %> widget widget-heading-simple text-white " onclick="pulse_it($(this))">
						<div class="widget-body innerAll inner-2x">
							<i class="fa fa-thumbs-up fa fa-4x pull-left fa fa-muted"></i>
							<div>								
								<% vote.reply_deeds.group_by(&:deed).each do |deed, reply_deeds| %>
									<h2 class="innerAll center strong"><%= deed %></h2>
									<% if !deed.description.blank? %>
										
									<div class="widget innerAll inner-2x text-inverse">										
										<h3 class="center"><%= deed.description %></h3>
									</div>
									<% end %>
								<% end %>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>
				<% end %>
				<% end %>
				<!-- // Tab content END -->
				<!-- Tab content -->
				<div id="tab4-5" class="tab-pane box-generic">					
					<h1>Ranking de Ações</h1>
					<div class="widget"></div>
					<div class="innerAll inner-2x">						
						<% @deed_ranking.each.each_with_index do |ranking, index| %>
						<h2><%= index + 1  %> - <%= ranking[:deed] %> </h2>
						<% end %>
					</div>
				</div>
				<div id="tab4-6" class="tab-pane box-generic">				
					<h1>Gráfico</h1>
					<div class="widget"></div>
					<div class="innerAll inner-2x">
						<% @questions.each do |question| %>					
						<div onclick="ver_grafico_<%= question.id  %>()" class="btn btn-info pull-right btn-sm"> Ver Gráfico</div>
							<%= render partial:'home/chart_question', locals:{votes:question.votes_theme_ranking(@theme, @event).each, question:question} %>
						<% end %>
					</div>
				</div>
				<div id="tab4-7" class="tab-pane box-generic">				
					<h1>Ranking de Desafios</h1>
					<div class="widget"></div>
					<div class="innerAll inner-2x">
						<% @questions.each do |question| %>					
						<% question.votes_theme_ranking(@theme, @event).each_with_index do |vote, index| %>
							<%= render partial:'home/votes_question_plenaria', locals:{index:index, vote:vote} %>
							<% end %>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= content_for :scripts do %>
	<script type="text/javascript">
	function pulse_it (el) {
		el.addClass('animated pulse');
		setTimeout(
			function(){
				el.removeClass('animated pulse');
			}
		, 1300);
	}
	</script>
<% end %>